# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop


# Mod Properties
mod_version=1.0.1
maven_group=bikerboys.nop
archives_base_name=no-offhand-placing


minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.150.0+26.1.2
        






